### ISSUE TITLE
Image in README is broken

### ISSUE THREAD

**Issue by saltorre** [bancolombia/dart-code-linter#109]
**Describe the error**

The image in the README is a broken link.

**How ​​to replicate the bug**
Step by step to reproduce the error:
1. Click on the link "VS Code Example".

**Screen shots**
![image](https://github.com/bancolombia/dart-code-linter/assets/7422314/93734c02-4698-4262-84cb-b3625511011c)

Browser window shows:

```
AccessDeniedAccess DeniedZW994GXC0FM1PXTT7lO9Xuy3NQ/kgmjk1A/P33VUibGZEK82Et0yA9RFVTNNnCOeCSycCKJvqdZNtfCLDd0AUEsTNe7R/T0RFDd+ww==
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>ZW994GXC0FM1PXTT</RequestId>
<HostId>7lO9Xuy3NQ/kgmjk1A/P33VUibGZEK82Et0yA9RFVTNNnCOeCSycCKJvqdZNtfCLDd0AUEsTNe7R/T0RFDd+ww==</HostId>
...
</Error>
```

**Runtime environment**
 - OS: iOS M1
 - Browser: chrome
 - Version: 118.0.5993.117 (Official Build) (arm64)

**Comment by santitigaga** [comment]
@saltorre thanks for finding the problem, this is now resolved.
