### ISSUE TITLE
old version of uuid

### ISSUE THREAD

**Issue by alirezat66** [bancolombia/dart-code-linter#116]
Because every version of dart_code_linter depends on uuid ^3.0.7 and
  **** depends on uuid ^4.2.2, dart_code_linter is forbidden.
So, because **** depends on dart_code_linter any, version solving
  failed.
  this is the error that I get when I try to get your package.

**Comment by santitigaga** [comment]
Hello this was solved in PR #54 , in dart code linter version 1.1.3 you will find the solution.

Greetings.
