### ISSUE TITLE
High CPU usage on VSCode, endless analyzing loop

### ISSUE THREAD

**Issue by juandiago** [bancolombia/dart-code-linter#117]
**Describe the error**
Hey! First of all, thanks for your package. 
I noticed that on my project using vscode with `dart_code_linter` enabled, I have and endless "analyzing" loop that hogs my CPU  and kills my lp battery. Any idea what might be causing this? As soon as I remove `dart_code_linter` from my yaml. configuration, everything returns to normal. 

**How ​​to replicate the bug**
Step by step to reproduce the error:
1. Open a project on vscode
2. Enable `dart_code_linter` 
3. Watch the analyzer server running in a loop

**Runtime environment**
 - OS: macOS Ventura
- VSCode: 1.85.1(using devcontainers, but I have also noticed it using a local instance)

Happy to help, If you guys need more information

**Comment by juandiago** [comment]
Updating to Flutter 3.16.5(Dart 3.2.3) seems to fix the issue. I was using Flutter 3.13.5.

Closing.

**Comment by juandiago** [comment]
on closer examination, issue is still present on 3.16.5

EDIT: seems to be vscode related, I'll try to gather more information....

**Comment by santitigaga** [comment]
@juandiago  Hello, can you try the new release please
