### ISSUE TITLE
Version 1.1.2 does not work. Static analysis fails

### ISSUE THREAD

**Issue by LiLatee** [bancolombia/dart-code-linter#122]
**Describe the error**
Version 1.1.2 depends on analyzer ^6.0.0 in which deprecated fields have been removed.

**How ​​to replicate the bug**
Step by step to reproduce the error:
1. Just try to use version 1.1.2

**Screen shots**
<img width="873" alt="image" src="https://github.com/bancolombia/dart-code-linter/assets/30510627/f2c2f5e4-6fd9-40ad-8bda-1bfcae2245fb">

<img width="801" alt="image" src="https://github.com/bancolombia/dart-code-linter/assets/30510627/98609807-83fe-4195-8238-c43d78f0d9bb">

**Comment by santitigaga** [comment]
@LiLatee you are right, please test the latest release.
