### ISSUE TITLE
Setup Dependabot or Renovate

### ISSUE THREAD

**Issue by quoc-huynh-cosee** [bancolombia/dart-code-linter#124]
It would be great if we add [Dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide) or [Renovate](https://github.com/renovatebot/tutorial?tab=readme-ov-file) to this repository, so that we'll get a PR if there are dependency updates.

**Comment by santitigaga** [comment]
hello @quoc-huynh-cosee,  great idea  I create pull request to do that #129

**Comment by quoc-huynh-cosee** [comment]
Hello @santitigaga,
can I contribute to this project? I can check the compatibility of the PRs created by Dependabot and merge them if you make me a contributor.
