### ISSUE TITLE
Analysis report is not being written to a file

### ISSUE THREAD

**Issue by nishiths23** [bancolombia/dart-code-linter#156]
**Describe the error**
`dart run dart_code_linter:metrics analyze --reporter=json --json-path="./report.json" lib ` is not generating a report file

**How ​​to replicate the bug**
Step by step to reproduce the error:
1. run `dart run dart_code_linter:metrics analyze --reporter=json --json-path="./report.json" lib`

**Runtime environment**
 - OS: Mac
 - Version: 1.1.5

**Comment by santitigaga** [comment]
@nishiths23 you are right I fix that in the next PR

**Comment by santitigaga** [comment]
The problem occurs when the report has issues and  the command don't have the flags `--no-fatal-style,  --no-fatal-warnings, --no-fatal-performance  `
But don't worry, it is fixed in version 1.2.1
