### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by seljad** [bancolombia/dart-code-linter#19]
I have image_cropper package in my project. When I try to install dart_code_linter, I get this error:

`Because image_cropper >=5.0.0 depends on image_cropper_platform_interface ^5.0.0 which depends on http ^1.0.0, image_cropper >=5.0.0 requires http ^1.0.0.
And because every version of dart_code_linter depends on http ^0.13.5, image_cropper >=5.0.0 is incompatible with dart_code_linter.
So, because the App depends on both image_cropper ^5.0.0 and dart_code_linter any, version solving failed.`.

Please update your dependencies.

**Comment by hohlfma** [comment]
Same here with http package: we are using current http version 1.1.0 but dart_code_linter still requires version 0.13.5

So +1 for upgrading the dependencies!

**Comment by The-Redhat** [comment]
This is fixed on the branch. @santitigaga can you please create a new version on pub.dev

**Comment by JTorkk** [comment]
Please also update uuid to the newest (4.2.1).

**Comment by The-Redhat** [comment]
ping @santitigaga

**Comment by bastislack** [comment]
I also have a dependency version problem with `uuid`: `Because every version of dart_code_linter depends on uuid ^3.0.7 and my_project depends on uuid ^4.1.0, dart_code_linter is forbidden.`

**Comment by rubenlop88** [comment]
The `analyzer` dependency was changed to `6.0.0` which introduces many breaking changes. The project right now does not compile. I think that change should be reverted.

**Comment by santitigaga** [comment]
Hi all, sorry for the delay in replying. I reverted the change of the dependency analyzer from version 6 to version 5, adjusted the failed unit tests and added this control in the CI pipeline.  #139 

Once the pull request is completed a new version will be generated.
