### ISSUE TITLE
The package doesn't support the "fix" command.

### ISSUE THREAD

**Issue by juan-campuzano** [bancolombia/dart-code-linter#21]
**Description**
Currently the package doesn't support the "fix" command, if you run ``` metrics fix <directory> ```it will throw an error with the following: ```Usage: metrics analyze [arguments] <directories>```.

![image](https://github.com/bancolombia/dart-code-linter/assets/23410488/138b37b0-568c-4728-98ba-fd92c27449a6)

**Why do you consider it necessary?**
It would be very valuable to have this functionality since there are many rules that can be corrected with this command and a lot of time that can be saved.

**Comment by byshy** [comment]
Related to #152
