### ISSUE TITLE
lint rule config settings not in docs

### ISSUE THREAD

**Issue by fredgrott** [bancolombia/dart-code-linter#23]
The lint rule configs for those lint rules that are configurable are not in the docs as of yet. Not a show stopping issue, just would be nice to have long term.

Thanks for correctly forking DCM and keeping it in operation.

**Comment by santitigaga** [comment]
Hello @fredgrott it is a pleasure to help the community.
The lint rule configs is defined here https://dcl.apps.bancolombia.com/.

If you find something missing please tell us
